export enum ResponseCode {
  // 정상
  OK = 'OK',

  // -------------------- 에러 응답 코드 --------------------

  // SignUp & Login
  NOT_VERIFIED_EMAIL = 'NOT_VERIFIED_EMAIL', // 인증되지 않은 이메일
  EMAIL_ALREADY_EXIST = 'EMAIL_ALREADY_EXIST', // 이미 가입된 이메일
  EMAIL_NOT_EXIST = 'EMAIL_NOT_EXIST', // 존재하지 않는 이메일
  SIGNED_BY_KAKAO = 'SIGNED_BY_KAKAO', // 카카오로 가입된 계정임
  SIGNED_BY_EMAIL = 'SIGNED_BY_EMAIL', // 이메일로 가입된 계정임
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT', // 이메일 형식 이상

  FAILED_TO_SEND_EMAIL = 'FAILED_TO_SEND_EMAIL', // Sendgrid로 이메일 전송 실패
  VERIFICATION_INFO_NOT_EXITS = 'VERIFICATION_INFO_NOT_EXITS', // 이메일과 인증번호가 일치하는 데이터 못찾음
  EXPIRED_VERIFICATION_CODE = 'EXPIRED_VERIFICATION_CODE', // 인증 번호 만료

  INVALID_USER_NAME_FORMAT = 'INVALID_USER_NAME_FORMAT', // 닉네임 형식 이상

  INVALID_PASSWORD_FORMAT = 'INVALID_PASSWORD_FORMAT', // 비밀번호 형식 이상
  WRONG_PASSWORD = 'WRONG_PASSWORD', // 비밀번호 틀림

  TERMS_NOT_AGREED = 'TERMS_NOT_AGREED', // 약관 동의 안 함

  SIGN_UP_FAILED = 'SIGN_UP_FAILED', // 회원가입 실패
  LOGIN_FAILED = 'LOGIN_FAILED', // 로그인 실패

  DELETED_USER = 'DELETED_USER', // 회원탈퇴된 계정

  // Auth
  USER_NOT_EXIST = 'USER_NOT_EXIST',

  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  AUTHENTICATION_EXPIRED = 'AUTHENTICATION_EXPIRED', // 토큰 만료

  GENERATE_TOKEN_FAILED = 'GENERATE_TOKEN_FAILED', // 토큰 생성 실패

  // Link
  INVALID_URL = 'INVALID_URL',

  // Cloud
  INVALID_NEW_POSITION = 'INVALID_NEW_POSITION',
  CREATE_CLOUD_FAILED = 'CREATE_CLOUD_FAILED',
  CLOUD_NOT_FOUND = 'CLOUD_NOT_FOUND',
  CREATE_CLOUD_MAXIMUM_20 = 'CREATE_CLOUD_MAXIMUM_20',

  // 404
  NOT_FOUND = 'NOT_FOUND',

  // 500
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // Unknown
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
