name: Deploy production server to cloudtype
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_ACC_TOKEN }}
      - name: Deploy server to cloudtype
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: linkloud/linkloud_backend
          stage: main
          yaml: >
            name: linkloud-server
            app: node@16
            context:
              git:
                ref: ${{ github.ref }}
                url: git@github.com:${{ github.repository }}.git
