name: Deploy production server to cloudtype
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_ACC_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: linkloud/linkloud_backend
          stage: main
          yaml: |-
            name: linkloud-server
            app: node@16
            options:
              ports: "8000"
              install: yarn
              build: yarn build
              start: yarn start:prod
              env:
                - name: MODE
                  value: production
                - name: PORT
                  value: 8000
                - name: TZ
                  var: TZ
                - name: DB_HOST
                  secret: DB_HOST
                - name: DB_PORT
                  secret: DB_PORT
                - name: DB_USERNAME
                  secret: DB_USERNAME
                - name: DB_PASSWORD
                  secret: DB_PASSWORD
                - name: DB_NAME
                  secret: DB_NAME
                - name: SENDGRID_API_KEY
                  secret: SENDGRID_API_KEY
                - name: SWAGGER_USER
                  secret: SWAGGER_USER
                - name: SWAGGER_PASSWORD
                  secret: SWAGGER_PASSWORD
                - name: KAKAO_REST_API_KEY
                  secret: KAKAO_REST_API_KEY
                - name: KAKAO_SIGNUP_REDIRECT_URI
                  secret: KAKAO_SIGNUP_REDIRECT_URI
                - name: KAKAO_LOGIN_REDIRECT_URI
                  secret: KAKAO_LOGIN_REDIRECT_URI
                - name: JWT_SECRET_KEY
                  secret: JWT_SECRET_KEY
                - name: LOGZIO_TOKEN
                  secret: LOGZIO_TOKEN
                - name: SENTRY_DSN
                  secret: SENTRY_DSN
                - name: SLACK_WEBHOOK_URL_FOR_SENTRY
                  secret: SLACK_WEBHOOK_URL_FOR_SENTRY
                - name: CLIENT_URL
                  secret: CLIENT_URL
                - name: HOST
                  secret: HOST
            context:
              git:
                ref: ${{ github.ref }}
                url: git@github.com:${{ github.repository }}.git
