name: Deploy production server to cloudtype
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_ACC_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: linkloud/linkloud_backend
          stage: main
          yaml: >
            name: linkloud-server
            app: node@16
            options:
              ports: "443"
              install: yarn
              build: yarn build
              start: yarn start:prod
              env:
                - name: MODE
                  value: production
                - name: PORT
                  value: 443
                - name: TZ
                  value: Asia/Seoul
                - name: DB_HOST
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_DB_HOST }}
                - name: DB_PORT
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_DB_PORT }}
                - name: DB_USERNAME
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_DB_USERNAME }}
                - name: DB_PASSWORD
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_DB_PASSWORD }}
                - name: DB_NAME
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_DB_NAME }}
                - name: SENDGRID_API_KEY
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_SENDGRID_API_KEY }}
                - name: SWAGGER_USER
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_SWAGGER_USER }}
                - name: SWAGGER_PASSWORD
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_SWAGGER_PASSWORD }}
                - name: KAKAO_REST_API_KEY
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_KAKAO_REST_API_KEY }}
                - name: KAKAO_SIGNUP_REDIRECT_URI
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_KAKAO_SIGNUP_REDIRECT_URI }}
                - name: KAKAO_LOGIN_REDIRECT_URI
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_KAKAO_LOGIN_REDIRECT_URI }}
                - name: JWT_SECRET_KEY
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_JWT_SECRET_KEY }}
                - name: LOGZIO_TOKEN
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_LOGZIO_TOKEN }}
                - name: SENTRY_DSN
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_SENTRY_DSN }}
                - name: SLACK_WEBHOOK_URL_FOR_SENTRY
                  value: ${{ secrets.CLOUDTYPE_PROD_ENV_SLACK_WEBHOOK_URL_FOR_SENTRY }}
            context:
              git:
                ref: ${{ github.ref }}
                url: git@github.com:${{ github.repository }}.git
